"""Phase-2 contracts and utilities."""

from .pipeline import run_scenario_pipeline
from .output_contract import (
    build_run_id,
    expected_phase2_run_artifact_paths,
    expected_phase2_run_output_paths,
    get_phase2_output_contract,
    parse_run_id,
    validate_phase2_run,
)
from .params import (
    default_phase2_params_dir,
    load_phase2_params,
    load_phase2_params_from_project,
)
from .constraints import (
    ConstraintConfig,
    get_constraints_schema,
    parse_constraints_config,
    validate_constraints_against_truth,
    validate_constraints_config,
    validate_constraints_for_run,
)
from .selection import (
    SelectionConfig,
    assign_latent_traits,
    build_phase1_entity_view,
    filter_scenario_population,
    generate_scenario_population_from_files,
    get_selection_schema,
    parse_selection_config,
    select_scenario_population,
    validate_selection_config,
)
from .event_grammar import (
    ACTIVE_EVENT_TYPES,
    COHABIT_MODES,
    CUSTODY_MODES,
    OPTIONAL_LATER_EVENT_TYPES,
    TRUTH_EVENTS_REQUIRED_COLUMNS,
    get_truth_event_grammar,
    validate_truth_events_dataframe,
    validate_truth_events_parquet,
)
from .simulator import (
    SimulationConfig,
    get_simulation_schema,
    parse_simulation_config,
    simulate_truth_layer,
)
from .emission import (
    DatasetNoiseConfig,
    EmissionConfig,
    MATCH_MODES,
    emit_observed_datasets,
    get_emission_schema,
    parse_emission_config,
)
from .quality import (
    QualityConfig,
    compute_phase2_quality_report,
    get_quality_schema,
    parse_quality_config,
)
from .scenario_catalog import (
    get_scenario_catalog_by_id,
    get_scenario_catalog_entries,
    get_scenario_catalog_summary,
    load_scenario_catalog,
)

__all__ = [
    "run_scenario_pipeline",
    "build_run_id",
    "expected_phase2_run_artifact_paths",
    "expected_phase2_run_output_paths",
    "get_phase2_output_contract",
    "parse_run_id",
    "validate_phase2_run",
    "default_phase2_params_dir",
    "load_phase2_params",
    "load_phase2_params_from_project",
    "ConstraintConfig",
    "get_constraints_schema",
    "parse_constraints_config",
    "validate_constraints_config",
    "validate_constraints_against_truth",
    "validate_constraints_for_run",
    "SelectionConfig",
    "get_selection_schema",
    "parse_selection_config",
    "validate_selection_config",
    "build_phase1_entity_view",
    "assign_latent_traits",
    "filter_scenario_population",
    "select_scenario_population",
    "generate_scenario_population_from_files",
    "ACTIVE_EVENT_TYPES",
    "OPTIONAL_LATER_EVENT_TYPES",
    "COHABIT_MODES",
    "CUSTODY_MODES",
    "TRUTH_EVENTS_REQUIRED_COLUMNS",
    "get_truth_event_grammar",
    "validate_truth_events_dataframe",
    "validate_truth_events_parquet",
    "SimulationConfig",
    "get_simulation_schema",
    "parse_simulation_config",
    "simulate_truth_layer",
    "DatasetNoiseConfig",
    "EmissionConfig",
    "MATCH_MODES",
    "get_emission_schema",
    "parse_emission_config",
    "emit_observed_datasets",
    "QualityConfig",
    "get_quality_schema",
    "parse_quality_config",
    "compute_phase2_quality_report",
    "load_scenario_catalog",
    "get_scenario_catalog_entries",
    "get_scenario_catalog_by_id",
    "get_scenario_catalog_summary",
]
